# 实验设置
model: FTragrec
dataset: Amazon_Beauty

# 数据集配置
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id

# 加载列设置
load_col:
    inter: [user_id, item_id, rating, timestamp]

# 数据过滤设置
min_user_inter_num: 5
min_item_inter_num: 5

# 训练参数
epochs: 100
train_batch_size: 1024
learner: adam
learning_rate: 0.001  # 提高学习率，帮助更快收敛
training_neg_sample_num: 0  # CE损失不需要负采样
eval_step: 1
stopping_step: 5
weight_decay: 0.0001  # 添加轻微正则化

# 评估参数
eval_batch_size: 256
topk: [5, 10, 20, 50]
metrics: ['Recall', 'MRR', 'NDCG']
valid_metric: MRR@10
eval_setting: TO_LS,full  # 按时间排序，留一法划分，全排序

# 模型参数 - 与DuoRec保持一致
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'  # 使用CE损失

# 与DuoRec兼容的参数
contrast: 'us_x'  # 与DuoRec保持一致
tau: 1
sim: 'dot'
lmd: 0.1
lmd_sem: 0.1

# 检索参数
len_lower_bound: -1  # 只使用长度≥5的序列
len_upper_bound: -1
len_bound_reverse: True  # 保留符合条件的序列，而不是排除它们
nprobe: 8  # 增加探测数量，提高检索质量
top_k: 8  # 增加检索数量

# RetrieverEncoder参数
retriever_layers: 2
retriever_temperature: 0.2  # 提高温度参数，使概率分布更平滑
retriever_dropout: 0.3  # 增加dropout，减少过拟合
retriever_update_interval: 6  # 更频繁地更新FAISS索引
kl_weight: 0.3  # 增加KL散度损失权重

# 目录设置
log_root: "./log/"
data_path: "./recbole/dataset/"

# 预训练设置
pretrain: False  # 由命令行参数控制


# retrieval settings for prediction
use_retrieval_for_predict: True  # 是否在预测时使用检索增强
predict_retrieval_alpha: 0.3     # 检索增强混合权重
predict_retrieval_temperature: 0.1  # 注意力温度参数